language: node_js
node_js:
  - "18"

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm run build

script:
  - npm run test

notifications:
  email:
    recipients:
      - thabangh647+travisCI@gmail.com
    on_success: always # options: `always`, `never`, or `change`
    on_failure: never
